### ISSUE TITLE
Add new PIFs on pif.gov

### ISSUE THREAD

**Issue by stroupaloop** [presidential-innovation-fellows/dev-standup#13]

**Comment by rossdakin** [comment]
Erren and Emily just need to commit, push, and ship — will work with them
in that tomorrow.

Helping SteBa get a dev environment, etc. up and running next week.

On Tuesday, October 20, 2015, Andrew Stroup <notifications@github.com>
wrote:

> Assigned #13
> <https://github.com/presidential-innovation-fellows/dev-standup/issues/13>
> to @rossdakin <https://github.com/rossdakin>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/presidential-innovation-fellows/dev-standup/issues/13#event-440689716>
> .
>


-- 

Ross Dakin
Presidential Innovation Fellow
whitehouse.gov/innovationfellows
(202) 286-0143
ross.dakin@pif.gov

**Comment by stroupaloop** [comment]
awesome, thanks @rossdakin , moving this (and all other 20% project stuff) to Trello based on meeting
